
### GET request to see all users
GET http://localhost:8080/users

### GET request to see User with specific ID
GET http://localhost:8080/users/2

### GET total number of users
GET http://localhost:8080/users/total

### GET user by LastName
GET http://localhost:8080/users/lastname/Lewandowska


### POST request to add user
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "firstName": "Jacek",
  "lastName": "Krzynowek",
  "email": "krzynowek@mail",
  "password": "Krzynowek10",
  "roleIds": [1]
}

### Update User via ID
PUT http://localhost:8080/users/edit/19
Content-Type: application/json

{
  "id": 19,
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@example.com",
  "roleIds": [1, 2]
}

### Update User Email
PUT http://localhost:8080/users/20/email
Content-Type: application/json

{
  "email": "newemail@example.com"
}

###DELETING
DELETE http://localhost:8080/users/delete/19
