###GET all events
GET http://localhost:8080/events/all

###GET event by id
GET http://localhost:8080/events/20

###GET event by organizer
GET http://localhost:8080/events/organizer/Tech Events Poland

###GET event by location
GET http://localhost:8080/events/locations/6

### GET events by city
GET http://localhost:8080/events/cities/Warszawa
Accept: application/json

###POST request to server
POST http://localhost:8080/events/add
Content-Type: application/json

{
  "title": "Small Discussion Panel",
  "organizer": "Java School",
  "startAt": "2025-09-15T17:09:00",
  "endAt": "2025-09-16T16:09:00",
  "capacity": 5,
  "location": {
    "id": 12
  },
  "user": {
    "id": 2
  },
  "tags": [
    {"id": 3},
    {"id": 6},
    {"id": 7}
  ]
}

###PUT request to update event
PUT localhost:8080/events/update/19
Content-Type: application/json

{
  "title": "JPA Masterclass",
  "organizer": "Java Teaching Academy",
  "startAt": "2025-12-10T09:00:00",
  "endAt": "2025-12-10T17:00:00",
  "capacity": 100,
  "location": {
    "id": 10
  },
  "user": {
    "id": 1
  },
  "tags": [
    {"id": 2},
    {"id": 4}
  ]
}

###DELETE request
DELETE localhost:8080/events/delete/15

