###GET all events
GET http://localhost:8080/events/all

###GET event by id
GET http://localhost:8080/events/20

###GET event by organizer
GET http://localhost:8080/events/organizer/Tech Events Poland

###GET event by location
GET http://localhost:8080/events/locations/6

### GET events by city
GET http://localhost:8080/events/cities/Warszawa
Accept: application/json

###POST request to server
POST http://localhost:8080/events/add
Content-Type: application/json

{
  "title": "Full-Stack Web Development Bootcamp",
  "organizer": "CodeCraft Academy",
  "startAt": "2025-10-15T09:00:00",
  "endAt": "2025-12-15T16:00:00",
  "capacity": 35,
  "location": {
    "id": 16
  },
  "user": {
    "id": 3
  },
  "tags": [
    {"id": 1},
    {"id": 4},
    {"id": 8},
    {"id": 11},
    {"id": 13}
  ]
}

###PUT request to update event
PUT localhost:8080/events/update/19
Content-Type: application/json

{
  "title": "JPA Masterclass",
  "organizer": "Java Teaching Academy",
  "startAt": "2025-12-10T09:00:00",
  "endAt": "2025-12-10T17:00:00",
  "capacity": 100,
  "location": {
    "id": 10
  },
  "user": {
    "id": 1
  },
  "tags": [
    {"id": 2},
    {"id": 4}
  ]
}

###DELETE request
DELETE localhost:8080/events/delete/15

