### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###GET ALL EVENTS
GET http://localhost:8080/events/all

###GET EVENT BY ID
GET http://localhost:8080/events/20

###GET EVENT BY ORGANIZER
GET http://localhost:8080/events/organizer/Tech Events Poland

###GET EVENTS BY LOCATION
GET http://localhost:8080/events/locations/6

### GET EVENTS BY CITY
GET http://localhost:8080/events/cities/Warszawa
Accept: application/json

###POST request to server
POST http://localhost:8080/events/add
Content-Type: application/json

{
  "title": "Spring Boot Advanced Workshop",
  "organizer": "Java Masters Academy",
  "startAt": "2025-10-15T10:15:00",
  "endAt": "2025-10-15T16:16:00",
  "capacity": 25,
  "location": {
    "id": 6
  },
  "user": {
    "id":5
  },
  "tags": [
    {"id": 1},
    {"id": 4},
    {"id": 7}
  ]
}


###PUT request
PUT localhost:8080/events/update/19
Content-Type: application/json

{
  "title": "JPA Masterclass",
  "organizer": "Java Sztos Academy",
  "startAt": "2025-12-10T09:00:00",
  "endAt": "2025-12-10T17:00:00",
  "capacity": 100,
  "location": {
    "id": 10
  },
  "user": {
    "id": 1
  },
  "tags": [
    {"id": 2},
    {"id": 4}
  ]
}

###DELETE request
DELETE localhost:8080/events/delete/15

