### GET all registrations
GET localhost:8080/registrations

### GET User registration by ID
GET localhost:8080/registrations/user/14

###POST to register for an event
POST localhost:8080/registrations/register?userId=1&eventId=21

###CANCEL registration
DELETE http://localhost:8080/registrations/37/cancel?userId=17

###DELETE entirely registration
DELETE http://localhost:8080/registrations/47/delete

