### GET request to see all users
GET http://localhost:8080/users

### GET request to see User with specific ID
GET http://localhost:8080/users/2

### GET total number of users
GET http://localhost:8080/users/total

### GET user by LastName
GET http://localhost:8080/users/lastname/Lewandowska

### POST request to add user
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "firstName": "Rebecca",
  "lastName": "Organizer",
  "email": "organizer@mail",
  "password": "Organizer123",
  "roleIds": [3]
}

### UPDATE user via ID
PUT http://localhost:8080/users/edit/2
Content-Type: application/json

{
  "id": 2,
  "firstName": "John",
  "lastName": "Admin",
  "email": "admin@mail.com",
  "roleIds": [2]
}

### UPDATE user email
PUT http://localhost:8080/users/20/email
Content-Type: application/json

{
  "email": "newemail@example.com"
}

###DELETE
DELETE http://localhost:8080/users/delete/19
